ERROR: could not call Lua callback: main.lua:8: bad argument #1 to 'create' (number expected, got table)

